CREATE TABLE TITLE(
	ID BIGINT UNIQUE NOT NULL,
	NAME VARCHAR(200) NOT NULL,
	DESCRIPTION TEXT,
	CONSTRAINT TITLE_PK PRIMARY KEY (ID),
	CONSTRAINT UC_TITLE_NAME UNIQUE (NAME)
);

CREATE TABLE MEMBER(
	ID BIGINT AUTO_INCREMENT,
	FIRST_NAME VARCHAR(100) NOT NULL,
	LAST_NAME VARCHAR(100) NOT NULL,
	PHOTO_URL TEXT,
	TITLE_ID BIGINT, 
	ACTIVE BIT DEFAULT 1,
	HIRE_DATE DATE,
	CONSTRAINT MEMBER_PK PRIMARY KEY (ID),
	CONSTRAINT FK_TITLE FOREIGN KEY (TITLE_ID) REFERENCES TITLE(ID)
);

CREATE TABLE CONTACT_TYPE(
	ID BIGINT UNIQUE NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PRIORITY INT NOT NULL DEFAULT 99,
	DESCRIPTION TEXT,
	CONSTRAINT CONTACT_TYPE_PK PRIMARY KEY (ID),
	CONSTRAINT UC_CONTACT_NAME UNIQUE (NAME)
);

CREATE TABLE MEMBER_CONTACT(
	ID BIGINT AUTO_INCREMENT,
	MEMBER_ID BIGINT NOT NULL,
	CONTACT_TYPE_ID BIGINT NOT NULL,
	VALUE VARCHAR(200) UNIQUE NOT NULL,
	CONSTRAINT MEMBER_CONTACT_PK PRIMARY KEY (ID),
	CONSTRAINT FK_CONTACT_TYPE FOREIGN KEY (CONTACT_TYPE_ID) REFERENCES CONTACT_TYPE(ID),
	CONSTRAINT FK_CONTACT_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID)
);

CREATE TABLE TECHNOLOGY(
	ID BIGINT AUTO_INCREMENT,
	NAME VARCHAR(200) NOT NULL,
	DISPLAY_NAME TEXT,
	DESCRIPTION TEXT,
	CONSTRAINT TECHNOLOGY_PK PRIMARY KEY (ID),
	CONSTRAINT UC_TECH_NAME UNIQUE (NAME)
);

CREATE TABLE MEMBER_TECHNOLOGY(
	ID BIGINT AUTO_INCREMENT,
	MEMBER_ID BIGINT NOT NULL,
	TECHNOLOGY_ID BIGINT NOT NULL,
	CONSTRAINT MEMBER_TECHNOLOGY_PK PRIMARY KEY (ID),
	CONSTRAINT FK_TECHNOLOGY FOREIGN KEY (TECHNOLOGY_ID) REFERENCES TECHNOLOGY(ID),
	CONSTRAINT FK_TECHNOLOGY_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID)
);